title:            Finally
description:      Laura and Zack are getting married.
logo:             site-logo.png
search:           true
#Comment out url when working locally to resolve base urls correctly
url:              #http://zlwedding.com

# Owner/author information
owner:
  name:           Zack Tollman
  avatar:         bio-photo.jpg
  email:          you@email.com

# Links to include in top navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: RSVP
    url: https://tollmanz.wufoo.com/forms/wedding-rsvp/
    external: true
  - title: Registry
    url: /registry
  - title: Wedding Information
    url: /wedding
  - title: Where to Eat
    url: /eat
  - title: Where to Stay
    url: /stay
  - title: What to Do
    url: /do

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Los_Angeles
future:      true
pygments:    true
markdown:    kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]